### ISSUE TITLE
type 'const GeographicLib::Geocentric' does not provide a call operator

### ISSUE THREAD

**Issue by Treffen** [ZoeLiLi/gtsam_imu#10]
Cmake error, could you help me solve this problem? thank you

/home/jys236/GTSAM_Test/gtsam_imu-master/src/gnss_class.cpp: In constructor ‘TADR::GNSSPara::GNSSPara(boost::shared_ptr<TADR::SensorFactors>)’:
/home/jys236/GTSAM_Test/gtsam_imu-master/src/gnss_class.cpp:11:70: error: no match for call to ‘(const GeographicLib::Geocentric) ()’
 , gnss_local_cartesian_(0.0,0.0,0.0,GeographicLib::Geocentric::WGS84())
                                                                      ^
CMakeFiles/multiple_sensor_fusion.dir/build.make:86: recipe for target 'CMakeFiles/multiple_sensor_fusion.dir/src/gnss_class.cpp.o' failed
make[2]: *** [CMakeFiles/multiple_sensor_fusion.dir/src/gnss_class.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/multiple_sensor_fusion.dir/all' failed
make[1]: *** [CMakeFiles/multiple_sensor_fusion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ZoeLiLi** [comment]
Make sure if you have install GeographicLib. If not, download from github, and install. Then try again.

**Comment by ZoeLiLi** [comment]
> Cmake error, could you help me solve this problem? thank you
> 
> /home/jys236/GTSAM_Test/gtsam_imu-master/src/gnss_class.cpp: In constructor ‘TADR::GNSSPara::GNSSPara(boost::shared_ptrTADR::SensorFactors)’:
> /home/jys236/GTSAM_Test/gtsam_imu-master/src/gnss_class.cpp:11:70: error: no match for call to ‘(const GeographicLib::Geocentric) ()’
> , gnss_local_cartesian_(0.0,0.0,0.0,GeographicLib::Geocentric::WGS84())
> ^
> CMakeFiles/multiple_sensor_fusion.dir/build.make:86: recipe for target 'CMakeFiles/multiple_sensor_fusion.dir/src/gnss_class.cpp.o' failed
> make[2]: *** [CMakeFiles/multiple_sensor_fusion.dir/src/gnss_class.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/multiple_sensor_fusion.dir/all' failed
> make[1]: *** [CMakeFiles/multiple_sensor_fusion.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

Make sure if you have install GeographicLib. If not, download from github, and install. Then try again
